### ISSUE TITLE
MathJax not firing with custom delimiters

### ISSUE THREAD

**Issue by PhilippImhof** [h5p/h5p-math-display#4]
I run H5P with math display library combined with Moodle 3.7.  MathJax is configured to use `$...$` and `$\( ... \)$` as delimiters for inline math and `$$ ... $$` and `\[ ... \]` as delimiters for display math.

However, if my H5P element does **only** contain `$` expressions, MathJax is not fired, it is not even loaded, as shown by the following test in Chrome's javascript console:

> MathJax.Hub.Typeset()
> Uncaught ReferenceError: MathJax is not defined
>     at <anonymous>:1:1

If I use at least one `\( ... \)` expression, everything works fine and **all** expressions are correctly rendered.

**Comment by otacke** [comment]
Hi @PhilippImhof!
The TeX shorthand using just one dollar symbol to enclose math wasn't implemented intentionally to avoid confusion for unexperienced people who may use dollar symbols within text, e.g. for math exercises using currencies. That's why it's [not listed in the documentation](https://h5p.org/mathematical-expressions) as well.

**Comment by PhilippImhof** [comment]
I think this is perfectly fine as a default. It is also the default for Moodle. However, Moodle offers a configuration option (`additionaldelimiters`) in the MathJax filter in order to activate MathJax parsing for custom delimiters.

Experienced people living in countries that do not use the dollar as their currency symbol should have an easy way to activate `$ ... $` in H5P's MathJax. Even more so, because it is possible to set up MathJax in H5P this way. I think the math display module should either check for the configuration in `H5P.MathDisplay` or add a configuration option allowing for custom delimiters.

Also, for Moodle, I would suggest an option similar to the one of Moodle's MathJax filter, allowing to set the configuration directly in the admin pages instead of directly editing `config.php`.

**Comment by otacke** [comment]
@PhilippImhof I understand.

Relying on the settings of MathJax to detect LaTeX was not done for two/three reasons, and the most relevant one probably is to not always load and run MathJax beforehand as most content probably doesn't require it. That's why H5P checks for potential delimiters before MathJax is loaded at all. They are set by a regular expression defined in https://github.com/h5p/h5p-math-display/blob/master/library.json that will find its way into the `addon` column in the `h5p_libraries` table of the database for the entry for `H5P.MathDisplay`. You could alter them in the database to suit your needs -- don't forget to add your delimiter to the MathJax settings as well. Downside: It's not update-proof, so whenever you update the MathDisplay library, you'll have to remember to update the regular expression as well.

As for your feature requests: They should go into the feature request forum at [https://h5p.org/forum/16](https://h5p.org/forum/16).

Cheers,
Oliver

**Comment by PhilippImhof** [comment]
Thank you for your explanations. I temporarily changed `library.json` and it works now. I will think of a better solution. Before adding a feature request, I will wait for Moodle 3.8 where H5P is going to be integrated as a core component. Let's see what this changes in terms of configuration and interface.
