### ISSUE TITLE
Integration with Moodle doesn't work?

### ISSUE THREAD

**Issue by roklipni** [h5p/h5p-math-display#7]
I have an issue using H5P-math-display on Moodle. We are using Moodle 3.10 and H5P-math-display version 1.0.6.; the config.php for Moodle has been updated with the recommended code.

In H5P it shows as regular text:

![MD1](https://user-images.githubusercontent.com/74645635/99497183-d8ca9680-2975-11eb-865a-76439d09d762.PNG)

Should I have done something else?

**Comment by otacke** [comment]
@roklipni You don't need to set anything in the config.php file unless you want to customize the settings. Sure you configured it correctly? You could simply revert those changes. Checking the developer console for errors would also be a good idea.

**Comment by roklipni** [comment]
@otacke thank you - I did start off without the config.php customization, but thought it would help. Reverting back doesn't change anything.
Developer console shows only:
![MD2](https://user-images.githubusercontent.com/74645635/99498955-7a52e780-2978-11eb-9b0a-2d9eae4fabe8.PNG)

**Comment by otacke** [comment]
@roklipni I don't see anything that would be related to MathDisplay. Are you checking on a page that contains H5P with LaTeX? Have you checked the network tab for probems, e.g. the MathDisplay library not being loaded?

**Comment by roklipni** [comment]
@otacke I am on a page using LaTeX code. I have added the same code to the description and it shows properly:

![MD3](https://user-images.githubusercontent.com/74645635/99499846-cc483d00-2979-11eb-876a-8ff63a09a7e4.PNG)

And yet, using H5P I see MathJax.js?delayStartupUntil=configured
So should H5P MathJax have been configured somewhere as well?

**Comment by roklipni** [comment]
... but Mathdisplay.js is not seen as loaded in the Network tab.

**Comment by otacke** [comment]
@roklipni You seem to be loading MathJax in moodle (with some delay parameter), too. That might potentially create a conflict when the library tries to load MathJax itself.

**BUT** if it's not loaded at all (can't see the complete list of files), then the problem is probably not with the H5P MathDisplay library but with the H5P core: Are you using the H5P plugin or moodle's native core version shipped as of moodle 3.8? The moodleHQ didn't implement all features that the H5P plugin has. For instance, it does not have the customization hooks, and I assume that they also did not port the addon feature that the MathDisplay library uses.

**Comment by roklipni** [comment]
@otacke I am using the plugin itself, version 1.21.0, and the H5P from Moodle is removed from our installation.

I have removed the test description using MathJax, and I can still see it loads MathJax:
![MD4](https://user-images.githubusercontent.com/74645635/99505054-a07c8580-2980-11eb-9673-03ba9bc9a19f.PNG)

**Comment by otacke** [comment]
@roklipni 

Loading MathJax alone doesn't help, because H5P lives inside an iframe that MathJax cannot access from the outside. That's what the MathDisplay library is used for. When the H5P plugin core detects that LaTeX is used in H5P content, then and only then it loads the MathDisplay library which in turn will include MathJax (or KaTeX in the future possibly) inside the iframe.

Sorry, I am not a moodle expert - didn't even know that you could remove moodle's H5P core integration. Still, if the MathDisplay library is installed but not loaded at all (if LaTeX is used inside H5P content and it is in your case), then I don't think it's an issue with the library but with the particular integration - and I wouldn't know why the H5P plugin core wouldn't try to load the library.

**Comment by roklipni** [comment]
@otacke thank you for all your support. I guess I should move my problem to H5P Moodle plugin issues and seek help there.

**Comment by roklipni** [comment]
Not necessarily up to the H5P math.
